eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka-server
    fetch-registry: true
    register-with-eureka: true

logging:
  level: info
spring:
  application:
    name: api-gateway
#  cloud:
#    gateway:
#      routes:
