server:
  port: 8080

#  servlet:
#    context-path: product
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://${DB_HOST_NAME:localhost}:${DB_PORT:5432}/${DB_NAME:product}?createDatabaseIfNotExist=true
    username:
    password:
    driver-class-name: org.postgresql.Driver
#    tomcat:
#      test-while-idle: true
#      validation-query: 1

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka-server