server:
  port: 8081
spring:
  application:
    name: order-service
  datasource:
    username:
    password:
    url: jdbc:postgresql://${DB_HOST_NAME:localhost}:${DB_PORT:5432}/${DB_NAME:order_service}?createDatabaseIfNotExist=true
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka-server